apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-aggregator-deployment
  labels:
    app: service-aggregator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-aggregator-container
  template:
    metadata:
      labels:
        app: service-aggregator-container
    spec:
      containers:
      - name: service-aggregator-container
        image: kiel0103/ninedocs-service-aggregator:7
        imagePullPolicy: Always
